Update MVC lesson example, add MDN link to MVC
turingschool/front-end-curriculum pull request #727
Opened 2023-07-17 15:08 UTC by sertmer

This PR addressed issue #710 

## Summary of changes needed: 
- [x] The current lesson uses a class based component to describe the MVC pattern
- [x] This example needs to be updated to be a functional component
- [x] Any language in the lesson that is referring to that class based component may also need to be updated
- [x] The lesson should include a link to the MVC pattern architecture page on MDN

### Changes Made:

- [x] All of the above

### Questions
- Please review my react code - I was feeling a bit rusty!
- No other specific considerations

2023-07-18 15:35 UTC, hfaerber commented on lessons/module-3/mvc.md
> +  const [count, setCount] = useSate(0);
Just missing a 't' in state here :)

2023-07-19 17:45 UTC, hfaerber requested changes
Thanks for working on this Scott!  I made 2 comments on the code example.
Could you also edit the very end of the lesson please?
- In the **Wrapping it up** section, can you please remove "How does Redux play into this? Work on this for 10 minutes, then we’ll reconvene."
- In the **References** section, can you please stack the two links so its clear there are two?

2023-07-19 17:45 UTC, hfaerber commented on lessons/module-3/mvc.md
>  import React, { Component } from 'react';
We should be able to remove the {Component} import here

2023-07-19 21:30 UTC, sertmer commented on lessons/module-3/mvc.md
>  import React, { Component } from 'react';
✅

2023-07-19 21:30 UTC, sertmer commented on lessons/module-3/mvc.md
> +  const [count, setCount] = useSate(0);
Thank you! ✅

2023-07-19 21:33 UTC, sertmer commented
Thanks Heather! I made those changes and I'll merge it now!

2023-07-19 21:33 UTC, merged